apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # this defines which pods are going to be represented by this service
  # the service becomes a network endpoint for either other services
  # or external users
  selector:
    app: webapp
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30080

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  type: NodePort
  ports:
    - name: endpoint
      port: 61616
    - name: admin
      port: 8161
      nodePort: 30010

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  type: ClusterIP
  ports:
    - name: http
      port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  type: ClusterIP
  ports:
    - name: http
      port: 8080
