apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # this defines which pods are going to be represented by this service
  # the service becomes a network endpoint for either other services
  # or external users
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - name: http
      port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  type: ClusterIP
  ports:
    - name: endpoint
      port: 61616

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  type: ClusterIP
  ports:
    - name: http
      port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  type: ClusterIP
  ports:
    - name: http
      port: 8080
